library soia;

import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';
import 'package:collection/collection.dart';
import 'package:convert/convert.dart';
import 'package:typed_data/typed_buffers.dart';
import 'package:http/http.dart' as http;

part 'src/binary_utils.dart';
part 'src/byte_string.dart';
part 'src/enum_serializer.dart';
part 'src/frozen_list.dart';
part 'src/iterable_serializer.dart';
part 'src/list_equality.dart';
part 'src/method.dart';
part 'src/mutable_list.dart';
part 'src/optional_serializer.dart';
part 'src/primitive_serializers.dart';
part 'src/record_id.dart';
part 'src/serializer.dart';
part 'src/serializers.dart';
part 'src/service.dart';
part 'src/service_client.dart';
part 'src/struct_serializer.dart';
part 'src/type_descriptor.dart';
part 'src/type_descriptor_parser.dart';
part 'src/type_visitor.dart';
part 'src/unix_epoch.dart';
part 'src/unrecognized.dart';
